special_symbols = {
    'Alpha': "A",
    'Epsilon': "E",
    'Zeta': "Z",
    'Eta': "H",
    'Iota': "I",
    'Kappa': "K",
    'Mu': "M",
    'Nu': "N",
    'Rho': "P",
    'Tau': "T",
    'Chi': "X",
    "complexes": "\\mathbb{C}",
    "reals": "\\mathbb{R}",
    "rationals": "\\mathbb{Q}",
    "integers": "\\mathbb{Z}",
    "naturals": "\\mathbb{N}",
    "infinity": "\\infty",
}
